server:
    port: 9003

spring:
    application:
        name: book-service

#    elasticsearch:
#        uris: http://es01:9200

#    elasticsearch:
#        host: es01
#        uri: 9200
#        ssl:
#            enabled: true
#            truststore-path: classpath:ca.crt
#            truststore-password: GQ7wpccv9U-ccS4bpkAc
#            truststore-username: elastic

#    elasticsearch:
#        uris: https://es01:9200
#        username: elastic
#        password: GQ7wpccv9U-ccS4bpkAc
#        ssl:
#          truststore-location: classpath:ca.crt
#          truststore-password: GQ7wpccv9U-ccS4bpkAc




    datasource:
        url: jdbc:postgresql://postgresbook:5432/bookdb
        username: book
        password: book

    jpa:
        hibernate:
            ddl-auto: update
    data:
        mongodb:
            authentication-database: admin
            username: root
            password: admin
            database: Log
            port: 27017
            host: mongo
    kafka:
        bootstrap-address: kafka:9092
        bootstrap-servers: kafka:9092
        consumer:
            group-id: book-service
            auto-offset-reset: latest
            bootstrap-servers: kafka:9092
            properties:
              spring.json.trusted.packages: com.project.*
        topics: {
            loan-book: loan-book,
            loan-succes: loan-succes,
            loan-fail: loan-fail
        }

    jackson:
        serialization:
            indent-output: true
#    main:
#        allow-bean-definition-overriding: true
